# .circleci/config.yml
version: 2.1
orbs:
  node: circleci/node@5
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install dependencies
          command: npm install --save
      - run:
          name: Run linter
          command: echo "Command -> 'npm run lint'"
      - run:
          name: Clean and package
          command: echo "Cleaning and packaging..."

  tests:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install jest-junit
      - run:
          name: Run unit tests
          command: npm run test:ci
      - store_test_results:
          path: ./test-results/
      - run:
          name: Run integration tests
          command: echo "Running integration tests..."
      - run:
          name: Run regression tests
          command: echo "Running regression tests..."
      - run:
          name: Run performance tests
          command: echo "Running performance tests..."
      - run:
          name: Run security tests
          command: echo "Running security tests..."
      - run:
          name: Run compatibility tests
          command: echo "Running compatibility tests..."
      - run:
          name: Run accessibility tests
          command: echo "Running accessibility tests..."

  deploy:
    parameters:
      environment:
        type: string
    executor: node/default
    steps:
      - checkout
      - run:
          name: Prepare Deployment Environment
          command: echo "Preparing deployment for <<parameters.environment>>..."
      - run:
          name: Deploy Application
          command: echo "Deploying application to <<parameters.environment>> environment..."
      - run:
          name: Run Verification Tests
          command: echo "Running verification tests..."
      - run:
          name: Run Functional Validation Tests
          command: echo "Running functional validation tests..."
      - run:
          name: Run Load Tests
          command: echo "Running load tests..."
      - run:
          name: Final Deployment Step
          command: echo "Finalizing deployment to <<parameters.environment>>..."
      - run:
          name: Monitoring and Follow-up
          command: echo "Starting monitoring and follow-up process..."

workflows:
  version: 2

  feature-hotfix:
    jobs:
      - build:
          filters:
            branches:
              only:
                - /^feature\/.*/
                - /^hotfix\/.*/
      - tests:
          requires:
            - build

  development:
    jobs:
      - build:
          filters:
            branches:
              only: develop
      - tests:
          requires:
            - build
          filters:
            branches:
              only: develop
      - deploy:
          name: deploy_dev
          requires:
            - tests
          filters:
            branches:
              only: develop
          environment: development

  integration:
    jobs:
      - build:
          filters:
            branches:
              only: integration
      - tests:
          requires:
            - build
      - deploy:
          name: deploy_int
          requires:
            - tests
          filters:
            branches:
              only: integration
          environment: integration

  production:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - tests:
          requires:
            - build
      - deploy:
          name: deploy_prod
          requires:
            - tests
          filters:
            branches:
              only: main
          environment: production
